/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Attachments: typeof import('./src/components/formElements/Attachments.vue')['default']
    DatePicker: typeof import('./src/components/formElements/DatePicker.vue')['default']
    Dropdown: typeof import('./src/components/formElements/Dropdown.vue')['default']
    DropdownDisplay: typeof import('./src/components/formElements/DropdownDisplay.vue')['default']
    DropdownMultiple: typeof import('./src/components/formElements/DropdownMultiple.vue')['default']
    FileUploadButton: typeof import('./src/components/formElements/FileUploadButton.vue')['default']
    ListItemDisplay: typeof import('./src/components/ListItemDisplay.vue')['default']
    ListItemEditor: typeof import('./src/components/ListItemEditor.vue')['default']
    ListPage: typeof import('./src/components/ListPage.vue')['default']
    Main: typeof import('./src/components/Main.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextField: typeof import('./src/components/formElements/TextField.vue')['default']
  }
}
